name: abasu
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  #google_maps_flutter: 1.0.6
  cloud_firestore: ^0.14.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  google_sign_in: ^4.5.3
  rxdart: ^0.25.0
  provider: ^4.3.2+3
  fluttertoast: ^7.1.5
  uuid: ^2.2.2
  intl: ^0.16.1
  image_cropper: ^1.3.1
  cached_network_image: ^2.3.3
  image_picker: ^0.6.7+3
  firebase_storage: ^5.0.1
  permission_handler: ^5.0.1+1
  flutter_native_image: ^0.0.5+2
  date_format: ^1.0.8
  flutter_svg: ^0.19.1
  quick_feedback: ^0.1.1
  progress_dialog: ^1.2.4
  flutter_paystack: ^1.0.4+1
  geolocator: ^6.1.6
  flutter_polyline_points: ^0.2.4
  google_maps_flutter: ^1.2.0
  #location: ^3.1.0
  responsive_framework: ^0.0.14
  flutter_rating_bar: ^3.2.0+1
  geocoding: ^1.0.5
  sticky_grouped_list: ^1.3.0
  photo_view: ^0.10.2
  get_it: ^1.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

